CREATE TABLE admin
(
  admin_id INT(75) NOT NULL AUTO_INCREMENT,
  username VARCHAR(75) NOT NULL,
  password VARCHAR(75) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
   updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (admin_id)
);

CREATE TABLE speciality
(
  spec_id INT(75) NOT NULL AUTO_INCREMENT,
  spec_name VARCHAR(75) NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (spec_id)
);

CREATE TABLE patient
(
    patient_id INT NOT NULL AUTO_INCREMENT,
  lastname VARCHAR(75) NOT NULL,
  email VARCHAR(75) NOT NULL, 
  firstname VARCHAR(75) NOT NULL,
  password VARCHAR(75) NOT NULL,
  YOB DATE NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (patient_id)
);

CREATE TABLE doctor
(
  doctor_id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(75) NOT NULL,
  password VARCHAR(75) NOT NULL,
  firstname VARCHAR(75) NOT NULL,
  lastname VARCHAR(75) NOT NULL,
  spec_id INT NOT NULL,
  active int(2) NOT NULL
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (doctor_id),
  FOREIGN KEY (spec_id) REFERENCES speciality(spec_id)
);